### ISSUE TITLE
Graphical issues with the web server

### ISSUE THREAD

**Issue by claire-elek** [klebgenomics/Kaptive#16]
Hi, I have been having issues with the graphical interface of the Kaptive web server and was hoping someone might know how to solve the issue. I have tried submitting jobs and every time I get a Proxy Error (image attached). To get the result I have to refresh the page, but this doesn't load the graphic of the cps locus for my Klebsiella genome (screenshot also attached), there is just a large blank space.

I have tried fixing the proxy issue, I have tried using a VPN, I have tried deleting cookies, and using 3 different browsers but nothing has worked. Does anyone know if there is a simple fix for this please? Thanks very much!

![Kaptive Proxy Error](https://user-images.githubusercontent.com/88827312/129175181-ccb52b02-db11-47e8-a7d5-2384e7dabd8e.png)
![Kaptive Result](https://user-images.githubusercontent.com/88827312/129175186-6367f4ac-7052-45f2-96f2-81b818b045a4.png)

**Comment by kelwyres** [comment]
Hi Claire, 

Unfortunately we are currently having a few technical difficulties with the server and awaiting additional tech support. We're under stay at home orders here in Melbourne so it's taking a little longer than usual to investigate the problem. Apologies for the inconvenience. If you are having trouble accessing the results table and it's Klebsiella genomes you are looking at, you might like to try Pathogenwatch (https://pathogen.watch/), which will allow you to upload your genomes and run Kaptive as well as Kleborate and various other useful analyses. However, Pathogenwatch doesn't provide the graphical K/O locus output.

Thanks,
Kelly

**Comment by claire-elek** [comment]
Hi Kelly,

Thanks so much for your quick response! I totally understand the complexity of trying to get things done while under stay at home orders and will keep an eye out for updates on when the problem has been fixed. The graphic in Kaptive is really nice as it identifies genes that aren't names in the downloadable output files (they are listed simply as glycosyltransferases for example, without the gene name like wcaN, or wclQ). Annotation programs aren't much help either so I'll run my genomes through Kaptive for now as it gives me most of the info I need, and I'll re-run them when the issues have been sorted.

Thanks again for your help and stay safe,
Claire

**Comment by tomdstanton** [comment]
Closing this issue as it refers to [Kaptive-Web](https://github.com/klebgenomics/Kaptive-Web)
