### ISSUE TITLE
Creating Locus References Database

### ISSUE THREAD

**Issue by ne1al** [klebgenomics/Kaptive#25]
Hi,
I am new to Kaptive. I wonder if there is an argument to help me create locus references database through Kaptive or if that you can add this input file into the Kaptive repo for the users to download.
Thank you

**Comment by katholt** [comment]
Hi there, do you mean you want to create a Kaptive database of loci from a new organism (ie other than Klebsiella pneumoniae or Acineobacter baumanii)?

This takes a fair bit of work, including manual curation, and is not something can be done within Kaptive.

Rafal Mastowy has shared code for automating the process of extracting cps & kps loci from genomes, which could be used as a starting point to generating a new database for use with Kaptive: [https://github.com/rmostowy/fastKaptive](https://github.com/rmostowy/fastKaptive)

Once created and curated, the new database can be passed to Kaptive using -k or --k_refs. See details in the wiki for format requirements for K reference databases: [https://github.com/katholt/Kaptive/wiki/How-to-run#locus-references](https://github.com/katholt/Kaptive/wiki/How-to-run#locus-references)

If you do create a new database, please consider sharing it in a GitHub repository for others to use, and we can link to it from the Kaptive repo (and, following testing, could also include it in [Kaptive-Web](https://kaptive-web.erc.monash.edu/) as we have done with the third-party V. parahaemolyticus database).

**Comment by ne1al** [comment]
I am actually working on _Klebsiella pneumoniae, Acinetobacter baumanii_, and _Pseudomonas aeruginosa._ I will let you know if I manage to create one for _Pseudomonas aeruginosa_. Thank you.

**Comment by tomdstanton** [comment]
Closing this issue as it's a question relating to database curation which is outlined in the docs.
